name: SmokeTP
main: me.waffletastic.SmokeTP.SmokeTP
version: 1.1_4
author: Waffletastic and Sluijsens
permissions:
  smoketp.smoke:
    description: Allows the smoke to show on teleport.
    default: false